baseurl = "/"
title = "Terrassa"
author = "Daniel Zaragoza (Danielkvist)"

defaultContentLanguage = "en"
language = "en-US"

theme = "terrassa"
themesDir = "../.."

[params]

[params.hero] # Hero options
    show = true
    background = "undraw_freelancer_b0my.svg"

[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "example@gmail.com"
    type = "email"

[params.contact] # Contact info
    email = "example@gmail.com"
    phone = "xxx xxx xxx"
    address = "419 Creek St. Revere, MA 02151"

[params.social] # Your social networks
    twitter = "https://twitter.com/john"
    facebook = "https://facebook.com/john"
    github = "https://github.com/john"
    gitlab = ""
    codepen = "https://codepen.io/john"
    instagram = "https://instagram.com/john"
    pinterest = ""
    youtube = "https://youtube.com/channel/john"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""