baseurl = "/"
title = "Terrassa"
author = "Daniel Zaragoza (Danielkvist)"
googleAnalytics = ""
defaultContentLanguage = "en"
language = "en-US"

theme = "terrassa"
themesDir = "../.."

[params]
    description = "Terrassa is a simple, fast and responsive theme for Hugo with a strong focus on accessibility made from scratch."
    favicon = "favicon.ico"

[params.hero] # Hero
    background = "undraw_freelancer_b0my.svg" # Leave empty for no background image

[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "example@gmail.com"
    type = "email" # Leave blank for other types of links

[params.form] # Contact form
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgLabel = "Write something"
    inputMsgName = "message"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = false # TODO:
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan 2, 2006"
    postsPerPage = 7 # TODO:

[params.contact] # Contact info
    email = "example@gmail.com"
    phone = "xxx xxx xxx"
    address = "419 Creek St. Revere, MA 02151"

[params.social] # Social networks
    twitter = "https://twitter.com/john"
    facebook = "https://facebook.com/john"
    github = "https://github.com/john"
    gitlab = ""
    codepen = "https://codepen.io/john"
    instagram = "https://instagram.com/john"
    pinterest = ""
    youtube = "https://youtube.com/channel/john"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
     [privacy.instagram]
        disable = false
        simple = false
     [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
     [privacy.vimeo]
        disable = false
        simple = false
     [privacy.youtube]
        disable = false
        privacyEnhanced = true