baseurl = "/"
title = "Terrassa"
author = "Daniel Zaragoza (Danielkvist)"

defaultContentLanguage = "en"
language = "en-US"

theme = "terrassa"
themesDir = "../.."

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]

[params.cta] # Call To Action 
    cta = "Contact"
    link = "example@gmail.com"
    type = "email"

[params.contact] # Contact info
    email = "example@gmail.com"
    phone = "xxx xxx xxx"
    address = ""

[params.social] # Your social networks
    twitter = "https://twitter.com/john"
    facebook = "https://facebook.com/john"
    github = "https://github.com/john"
    gitlab = ""
    codepen = "https://codepen.io/john"
    instagram = "https://instagram.com/john"
    pinterest = ""
    youtube = "https://youtube.com/channel/john"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""